name: Update fork
on:
  push:
    branches:
      - main
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: mozilla/bergamot-translator
      - name: Reset the default branch with upstream changes
        run: |
          git config --global user.email "anatal@gmail.com"
          git config --global user.name "Andre Natal"
          git remote add upstream https://github.com/browsermt/bergamot-translator.git
          git branch -vv
          git fetch upstream
          git branch -vv
          git merge -m "Merge remote-tracking branch 'upstream/main'" upstream/main --allow-unrelated-histories
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: upstream-changes
